# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718d7a288648dc5373de3154a515494ea05278e30587e1711f786dc1e90db0c81c4936567b09f4ccffffa7d09a8f025f3959c7334d5e047d57878a1ccb595518

test:
  secret_key_base: 65bf1ff20334b8163f1e070450727b71ec450094108143b474b58c414c2bd3b58224feb9bceb1725fa3a4a0c7dfa14d081ab91ee0610c99c01f3fdbc4266dfe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
